import { jsPDF } from "jspdf";

function stripInline(text: string) {
  return text
    .replace(/\*\*(.*?)\*\*/g, "$1")
    .replace(/\*(.*?)\*/g, "$1")
    .replace(/`{1,3}([^`]*)`{1,3}/g, "$1")
    .replace(/\[(.*?)\]\((.*?)\)/g, "$1 ($2)");
}

/** Renders markdown-ish assistant text into a clean, styled PDF and downloads it. */
export function exportMarkdownToPdf(markdown: string, heading = "Noqva AI Document") {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 56;
  const maxWidth = pageWidth - margin * 2;
  let y = margin;

  const newPageIfNeeded = (needed: number) => {
    if (y + needed > pageHeight - margin) {
      doc.addPage();
      y = margin;
    }
  };

  // Header band
  doc.setFillColor(13, 13, 13);
  doc.rect(0, 0, pageWidth, 90, "F");
  doc.setTextColor(238, 238, 238);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.text(heading.slice(0, 60), margin, 50);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(161, 161, 170);
  doc.text(`Generated by Noqva AI · ${new Date().toLocaleString()}`, margin, 70);
  y = 130;
  doc.setTextColor(20, 20, 20);

  const lines = markdown.split("\n");
  for (const raw of lines) {
    const line = raw.trimEnd();
    if (!line.trim()) {
      y += 10;
      continue;
    }

    let text = stripInline(line);
    let size = 11;
    let style: "normal" | "bold" = "normal";
    let indent = 0;

    const headingMatch = /^(#{1,4})\s+(.*)$/.exec(line);
    if (headingMatch) {
      const level = headingMatch[1]!.length;
      text = stripInline(headingMatch[2]!);
      size = level === 1 ? 17 : level === 2 ? 14.5 : 12.5;
      style = "bold";
      y += 8;
    } else if (/^\s*([-*+]|\d+\.)\s+/.test(line)) {
      text = "•  " + stripInline(line.replace(/^\s*([-*+]|\d+\.)\s+/, ""));
      indent = 14;
    } else if (/^>\s?/.test(line)) {
      text = stripInline(line.replace(/^>\s?/, ""));
      indent = 14;
    }

    doc.setFont("helvetica", style);
    doc.setFontSize(size);
    const wrapped = doc.splitTextToSize(text, maxWidth - indent) as string[];
    for (const w of wrapped) {
      newPageIfNeeded(size + 8);
      doc.text(w, margin + indent, y);
      y += size + 6;
    }
  }

  const stamp = new Date().toISOString().replace(/[:.]/g, "-");
  doc.save(`Noqva_Document_${stamp}.pdf`);
}
